[package]
edition = "2021"
name = "image_processing"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
dominant_color = "0.3.0"
log = "0.4.17"
md5 = "0.7.0"
rayon = "1.5.3"
serde = { version = "1.0.144", features = ["serde_derive"] }
image = "0.24.3"

