[package]
name = "config"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "config"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.83"
confy = "0.4.0"
rand = "0.8.5"
